CREATE SCHEMA staging;
GO

CREATE TABLE staging.pnad_covid_pessoa
(
    NU_ANO INT,
    NU_MES INT,
    UF CHAR(2),
    CO_MUNICIPIO INT,
    ID_DOMICILIO BIGINT,
    ID_PESSOA BIGINT,
    SEXO CHAR(1),
    IDADE INT,
    ESCOLARIDADE INT,
    OCUPACAO INT,
    RENDIMENTO DECIMAL(12,2),
    SINTOMAS INT,
    INTERNADO CHAR(1),
    TESTE_COVID CHAR(1),
    DT_CARGA DATETIME
);
